/**
 * Real engine output, for the client to render.
 *
 * These are regenerated by `make demo-regenerate`, never hand-edited. apps/mobile/README.md
 * is explicit that UI must be built against real Decisions rather than invented data shapes,
 * and until the API lands (Phase 3) this is how the client gets one.
 *
 * Distinct from `expected/`, which is an ASSERTION target and deliberately omits the
 * Decision because golden.yaml is already the engine's regression net. Nothing asserts
 * against these.
 */

import type { Decision, SignalSnapshot } from "@weyos/shared-schema";

import alex0 from "../decisions/alex/day-00.json";
import alex1 from "../decisions/alex/day-01.json";
import alex2 from "../decisions/alex/day-02.json";
import alex3 from "../decisions/alex/day-03.json";
import alex4 from "../decisions/alex/day-04.json";
import alex5 from "../decisions/alex/day-05.json";
import alex6 from "../decisions/alex/day-06.json";
import james0 from "../decisions/james/day-00.json";
import james1 from "../decisions/james/day-01.json";
import james2 from "../decisions/james/day-02.json";
import james3 from "../decisions/james/day-03.json";
import james4 from "../decisions/james/day-04.json";
import james5 from "../decisions/james/day-05.json";
import james6 from "../decisions/james/day-06.json";
import sarah0 from "../decisions/sarah/day-00.json";
import sarah1 from "../decisions/sarah/day-01.json";
import sarah2 from "../decisions/sarah/day-02.json";
import sarah3 from "../decisions/sarah/day-03.json";
import sarah4 from "../decisions/sarah/day-04.json";
import sarah5 from "../decisions/sarah/day-05.json";

import type { AppStateId, PersonaId } from "./types";

export interface DemoDay {
  persona: PersonaId;
  day_index: number;
  label: string;
  app_state: AppStateId;
  /** Rule ids whose conditions came out UNKNOWN. Not the same as "did not fire". */
  unevaluable: string[];
  /**
   * The input the Decision was computed from.
   *
   * Carried because a Decision deliberately holds no raw readings — deltas exist only as
   * prose inside `fired_rules[].because`, so a signal tile cannot be built from a Decision
   * alone. In Phase 3 this is what /v1/signals serves.
   */
  snapshot: SignalSnapshot;
  decision: Decision;
}

const DAYS: Record<PersonaId, readonly unknown[]> = {
  sarah: [sarah0, sarah1, sarah2, sarah3, sarah4, sarah5],
  james: [james0, james1, james2, james3, james4, james5, james6],
  alex: [alex0, alex1, alex2, alex3, alex4, alex5, alex6],
};

export function dayCount(persona: PersonaId): number {
  return DAYS[persona].length;
}

export function getDemoDay(persona: PersonaId, dayIndex: number): DemoDay {
  const days = DAYS[persona];
  const day = days[dayIndex];
  if (day === undefined) {
    throw new RangeError(
      `${persona} has ${days.length} scripted days; asked for index ${dayIndex}`,
    );
  }
  return day as DemoDay;
}

export function allDemoDays(persona: PersonaId): DemoDay[] {
  return DAYS[persona].map((d) => d as DemoDay);
}
